Translate plugin guide
reearth/docs.reearth.io pull request #42
Opened 2022-11-02 01:57 UTC by lavalse

2022-11-25 03:20 UTC, rot1024 requested changes
All spaces at the end of each sentence should be deleted.

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/recipes/accepting-properties-to-make-a-plugin-configurable-for-users.md
> +場所を入力すると、リーフレット マップにマーカーが配置されます。
```suggestion
場所を入力すると、Leaflet マップにマーカーが配置されます。
```

リーフレット -> Leaflet 
fix all "リーフレット"

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/recipes/screen-capture-and-print.md
> +すべてのHTML要素のスクリーンショットを取りたい場合は、プラグインコードでいくつかのサードパーティライブラリを実装してみてください。
```suggestion

```

It is not supposed to take screenshots of all elements for now. Fix the original text also.

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/recipes/showing-html.md
> +## リーフレットマップを表示
```suggestion
## Leaflet マップを表示
```

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/tutorial.md
>  │   test-widget.js
```suggestion
test-plugin
├ reearth.yml
└ test-widget.js    
```

Fix the original text also.

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/tutorial.md
> +Re:Earthにログインし、プロジェクトの設定ページを開きます。(まだプロジェクトを作成していない場合は、作成してください)
```suggestion
Re:Earthにログインし、プロジェクトの設定ページを開きます（まだプロジェクトを作成していない場合は、作成してください）。
```

- 日本語文内の全ての括弧は全角にしてください。
- 読点は括弧の後ろに移動してください。

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/tutorial.md
> +少し待ってから「プラグインがインストールされました。」というメッセージが表示されれば、プラグインは正常にインストールされています！
```suggestion
少し待ってから「プラグインがインストールされました」というメッセージが表示されれば、プラグインは正常にインストールされています！
```

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/tutorial.md
> +- やり方:さまざまな一般的なユースケースのプラグインを実装する方法について説明します
```suggestion
- レシピ集:さまざまな一般的なユースケースのプラグインを実装する方法について説明します
```

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/how-plugins-work.md
> +## まとめ
The table below this one is not translated

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/introduction.md
> +今のところ、以下に記載されている「ウィジェット」と「ブロック（インフォボックス内）」機能がプラグインで拡張可能です。
```suggestion
今のところ、以下に記載されている「ウィジェット」と「ブロック」（インフォボックス内）がプラグインで拡張可能です。
```

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/introduction.md
> +ウィジェットでは、ボタンなどを設置することができ、それをクリックすることで、さまざまなデータを表示したり、アクションを呼び出したりすることができます。
```suggestion
画面上に浮かぶウィジェットを表示することができます。ウィジェットは、画面の端や隅にボタンなどを自由に配置することができ、それをクリックすることで、さまざまなデータを表示したり、アクションを呼び出したりすることができます。
```

全体的にあまり改行しすぎないでください。一文を短くすることは有効ですが、短すぎても読みづらくなります。

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/plugin-editor.md
> +- ymlファイルの変更はまだサポートされていません（Re:Earthでプロジェクトを編集しているときに、右側のパネルに表示されるカスタマイズ可能なプラグインフィールドを記述するためのファイル）
```suggestion
- マニフェストファイルの変更はまだサポートされていません（Re:Earthでプロジェクトを編集しているときに、右側のパネルに表示されるカスタマイズ可能なプラグインフィールドを記述するための reearth.yml ファイル）
```

Fix the original text also.

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/plugin-editor.md
> +皆様からの、ご提案やアイディアをお待ちしております！是非Discord、もしくはGithubで議論しましょう！
```suggestion
皆様からの、ご提案やアイディアをお待ちしております！是非Discord、もしくはGitHubで議論しましょう！

```

Github -> GitHub

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/prerequisites.md
> +- [MDN Web Docs: Learn web development](https://developer.mozilla.org/en-US/docs/Learn)
```suggestion
- [MDN ウェブ開発を学ぶ](https://developer.mozilla.org/ja/docs/Learn)  
```

日本語版のMDNに差し替えました。

2022-11-25 03:20 UTC, rot1024 commented on i18n/ja/docusaurus-plugin-content-docs-plugin-guide/current/recipes/finding-layers-and-updating-property-of-a-layer.md
> +このオブジェクトのプロパティをみることで、上書き可能なプロパティを確認することができます。
```suggestion
プロパティオブジェクトの詳細はまだドキュメント化されていませんが、開発者ツールのコンソールで `reearth.layers.layers` を実行すると現在のレイヤーのオブジェクトを取得することができます。このオブジェクトのプロパティを読み取ることで、上書き可能なプロパティを確認することができます。
```

みる -> 読み取る

2022-12-08 01:12 UTC, airslice approved these changes

2022-12-08 01:22 UTC, merged